In [68]:
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
import numpy as np
df = pd.read_csv('heart.csv')

In [69]:
df.keys()

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [70]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [71]:
X = df
y = df.target

In [72]:
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [73]:
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [74]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[ 0.9521966 ,  0.68100522,  1.97312292, ..., -0.71442887,
        -2.14887271,  0.91452919],
       [-1.91531289,  0.68100522,  1.00257707, ..., -0.71442887,
        -0.51292188,  0.91452919],
       [-1.47415758, -1.46841752,  0.03203122, ..., -0.71442887,
        -0.51292188,  0.91452919],
       ...,
       [ 1.50364073,  0.68100522, -0.93851463, ...,  1.24459328,
         1.12302895, -1.09345881],
       [ 0.29046364,  0.68100522, -0.93851463, ...,  0.26508221,
         1.12302895, -1.09345881],
       [ 0.29046364, -1.46841752,  0.03203122, ...,  0.26508221,
        -0.51292188, -1.09345881]])

In [75]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=30)

In [76]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)
model.score(X_test, y_test)

1.0

In [77]:
from sklearn.decomposition import PCA
pca = PCA(0.95)

In [78]:
X_pca = pca.fit_transform(X)
X_pca.shape

(303, 3)

In [79]:
pca

PCA(n_components=0.95)

In [80]:
X_pca

array([[-1.22677260e+01,  2.87000191e+00,  1.49687780e+01],
       [ 2.68966168e+00, -3.98738629e+01,  8.78692964e-01],
       [-4.29506397e+01, -2.36395300e+01,  1.75962403e+00],
       [-1.09452061e+01, -2.84411011e+01, -7.04384432e+00],
       [ 1.06978583e+02, -1.58794356e+01, -1.48620192e+01],
       [-5.36475680e+01,  4.00036418e+00,  1.10873338e+01],
       [ 4.80817376e+01, -3.04335074e+00,  6.43781968e+00],
       [ 1.55656031e+01, -2.62780596e+01, -1.05741709e+01],
       [-4.54392787e+01, -7.43212190e+00,  4.33590865e+01],
       [-7.73167161e+01, -1.99120266e+01,  2.55063211e+01],
       [-6.94364572e+00, -9.17885448e+00,  9.87407028e+00],
       [ 2.84255482e+01,  8.46629286e+00, -5.23696217e+00],
       [ 1.92472904e+01, -2.24247073e+01, -5.30203984e-01],
       [-3.58059305e+01,  5.69886673e+00, -1.89493713e+01],
       [ 3.75882641e+01, -1.02616367e+01,  1.82426937e+01],
       [-2.80002577e+01, -9.64945056e+00, -9.49458217e+00],
       [ 9.29745575e+01, -2.42628592e+01

In [81]:
pca.explained_variance_ratio_

array([0.74751318, 0.15037261, 0.08459139])

In [82]:
sum(pca.explained_variance_ratio_[0:])

0.982477175812727

In [83]:
X_train_pca, X_test_pca, y_train, y_test = train_test_split(X_pca, y, test_size=0.2, random_state=30)

In [84]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train_pca, y_train)
model.score(X_test_pca, y_test)

0.6885245901639344

In [85]:
pca = PCA(n_components=4)
X_pca = pca.fit_transform(X)
X_pca.shape

(303, 4)

In [86]:
X_pca

array([[ -12.26772602,    2.87000191,   14.96877795,    6.89347835],
       [   2.68966168,  -39.87386288,    0.87869296,  -10.58355015],
       [ -42.9506397 ,  -23.63953003,    1.75962403,   -7.78646573],
       ...,
       [ -51.96328951,   13.32915476,   15.48747096,   11.63700525],
       [-114.75539232,   36.43980804,    0.12753846,    0.51110125],
       [ -10.39571246,  -23.29623822,    2.39349718,    7.18243668]])

In [87]:
pca.explained_variance_ratio_

array([0.74751318, 0.15037261, 0.08459139, 0.01621486])

In [88]:
sum(pca.explained_variance_ratio_)

0.9986920349598674

In [89]:
X_train_pca, X_test_pca, y_train, y_test = train_test_split(X_pca, y, test_size=0.2, random_state=30)
model = LogisticRegression(max_iter=1000)
model.fit(X_train_pca, y_train)
model.score(X_test_pca, y_test)

0.7213114754098361