In [5]:
#NumPy: it is Linear Algebra library for Python
import numpy as np
# Arrays in np
myList = [1,2,3]
myList


[1, 2, 3]

In [6]:
np.array(myList)

array([1, 2, 3])

In [7]:
myMatrix = [[21, 34, 53], [1,2,3], [90,0,101]]
myMatrix

[[21, 34, 53], [1, 2, 3], [90, 0, 101]]

In [8]:
np.array(myMatrix)

array([[ 21,  34,  53],
       [  1,   2,   3],
       [ 90,   0, 101]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.random.rand(2)

array([0.87556013, 0.82444257])

In [15]:
np.random.rand(5,3)

array([[0.13841032, 0.50372442, 0.78088064],
       [0.20239331, 0.08788648, 0.76223211],
       [0.44970694, 0.8003865 , 0.61988918],
       [0.42846648, 0.76026118, 0.06014685],
       [0.48000999, 0.59804529, 0.52854504]])

In [16]:
np.random.randint(1,100)

26

In [17]:
randarray = np.random.randint(0,50,10)
randarray

array([41, 17, 24, 40, 48, 17, 18, 13, 33, 49])

In [19]:
array = np.arange(25)
array.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
randarray.max()

49

In [21]:
array.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [22]:
array.dtype

dtype('int32')

In [25]:
# pandas glorifed excel
import pandas as pd
labels = ['a', 'b', 'c']
myList = [15,23,25]
array = np.array(myList)
dict = {'a':15, 'b':23, 'c':35}
labels
array
dict

{'a': 15, 'b': 23, 'c': 35}

In [26]:
pd.Series(data=myList)

0    15
1    23
2    25
dtype: int64

In [27]:
pd.Series(data=myList, index = labels)

a    15
b    23
c    25
dtype: int64

In [28]:
pd.Series(myList, labels)

a    15
b    23
c    25
dtype: int64

In [29]:
pd.Series(data=array, index = labels)

a    15
b    23
c    25
dtype: int32

In [30]:
series1 = pd.Series([10.0, 20, 30, 40], index = ['DFW', 'ORD', 'JFK', 'WAS'])
series1

DFW    10.0
ORD    20.0
JFK    30.0
WAS    40.0
dtype: float64

In [32]:
series2 = pd.Series([10, 20, 30, 40], index = ['DFW', 'ORD', 'LGA', 'WAS'])
series2

DFW    10
ORD    20
LGA    30
WAS    40
dtype: int64

In [33]:
series1 + series2

DFW    20.0
JFK     NaN
LGA     NaN
ORD    40.0
WAS    80.0
dtype: float64

In [34]:
# NaN = not a number
series2['DFW']

10

In [36]:
from numpy.random import randn
np.random.seed(101)
df = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [37]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [40]:
df[['W', 'Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [41]:
type(df['W'])

pandas.core.series.Series

In [49]:
df['WY'] = df['W'] + df['Y']
df

W         X         Y         Z        WY
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [52]:
df['W'] + df['Y']
df

W         X         Y         Z        WY
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [54]:
df.drop('WY', axis = 1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [55]:
df

W         X         Y         Z        WY
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [58]:
df.loc['A']

W     2.706850
X     0.628133
Y     0.907969
Z     0.503826
WY    3.614819
Name: A, dtype: float64

In [59]:
df.iloc[2]

W    -2.018168
X     0.740122
Y     0.528813
Z    -0.589001
WY   -1.489355
Name: C, dtype: float64

In [60]:
df.iloc[0]

W     2.706850
X     0.628133
Y     0.907969
Z     0.503826
WY    3.614819
Name: A, dtype: float64

In [61]:
df.loc['B', 'Z']

0.6059653494949336

In [62]:
df.loc[['A', 'B'], ['W', 'Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [63]:
df>0

W      X      Y      Z     WY
A   True   True   True   True   True
B   True  False  False   True  False
C  False   True   True  False  False
D   True  False  False   True  False
E   True   True   True   True   True

In [64]:
df[df>0]

W         X         Y         Z        WY
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118       NaN       NaN  0.605965       NaN
C       NaN  0.740122  0.528813       NaN       NaN
D  0.188695       NaN       NaN  0.955057       NaN
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [65]:
df[df['W']>0]

W         X         Y         Z        WY
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [66]:
df[df['W']>0][['Y', 'X']]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [67]:
df.reset_index()

index         W         X         Y         Z        WY
0     A  2.706850  0.628133  0.907969  0.503826  3.614819
1     B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
2     C -2.018168  0.740122  0.528813 -0.589001 -1.489355
3     D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
4     E  0.190794  1.978757  2.605967  0.683509  2.796762

In [68]:
'CA NY WY OR CO'.split()

['CA', 'NY', 'WY', 'OR', 'CO']

In [69]:
index = 'CA NY WY OR CO'.split()

In [70]:
df['States'] = index

In [71]:
df

W         X         Y         Z        WY States
A  2.706850  0.628133  0.907969  0.503826  3.614819     CA
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959     NY
C -2.018168  0.740122  0.528813 -0.589001 -1.489355     WY
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542     OR
E  0.190794  1.978757  2.605967  0.683509  2.796762     CO

In [72]:
df.set_index('States')

W         X         Y         Z        WY
States                                                  
CA      2.706850  0.628133  0.907969  0.503826  3.614819
NY      0.651118 -0.319318 -0.848077  0.605965 -0.196959
WY     -2.018168  0.740122  0.528813 -0.589001 -1.489355
OR      0.188695 -0.758872 -0.933237  0.955057 -0.744542
CO      0.190794  1.978757  2.605967  0.683509  2.796762

In [73]:
df

W         X         Y         Z        WY States
A  2.706850  0.628133  0.907969  0.503826  3.614819     CA
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959     NY
C -2.018168  0.740122  0.528813 -0.589001 -1.489355     WY
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542     OR
E  0.190794  1.978757  2.605967  0.683509  2.796762     CO

In [74]:
df = df.set_index('States')
df

W         X         Y         Z        WY
States                                                  
CA      2.706850  0.628133  0.907969  0.503826  3.614819
NY      0.651118 -0.319318 -0.848077  0.605965 -0.196959
WY     -2.018168  0.740122  0.528813 -0.589001 -1.489355
OR      0.188695 -0.758872 -0.933237  0.955057 -0.744542
CO      0.190794  1.978757  2.605967  0.683509  2.796762